### ISSUE TITLE
Is there a way to read a AnyConnectProfile.xml?

### ISSUE THREAD

**Issue by emailyc** [ethack/docker-vpn#5]
My organisation provides a .xml that contains all the configuration for running Cisco anyconnect client? Is there a way to read the .xml file?

**Comment by iharshulhan** [comment]
Hi @emailyc. Yes, there is an option **--xmlconfig** in [openconnect](https://www.infradead.org/openconnect/manual.html)

**Comment by ethack** [comment]
I just updated the `vpn.sh` script to handle this. I haven't tested it but you should be able to put your config file at `~/.vpn/profilename.xml`, `source vpn.sh`, and then run `openconnect profilename`. Replace "profilename" with whatever you want but the filename has to match what you pass to openconnect.

**Comment by giovannipizzi** [comment]
Hi! Thanks @ethack for this very nice package! I confirm that I could connect via the config file as you mentioned! Just wanted to add that 
- for AnyConnect (even on mac) the profile is at `/opt/cisco/anyconnect/profile/PROFILENAME.xml`
- I did a symlink of the file above to `~/.vpn/PROFILENAME.xml`; on macOS, I also had to go in the Docker configuration and add, under Resources -> File Sharing, that also `/opt` is shared
- In the command line, in my case, I have to add also the VPN server name: `openconnect PROFILENAME SERVERNAME`

Otherwise, it works! (I.e., I think this issue can be closed?)
