### ISSUE TITLE
Allow to start the docker container in daemon mode

### ISSUE THREAD

**Issue by giovannipizzi** [ethack/docker-vpn#6]
Would it be possible to add an option to start (optionally) the docker container in daemon mode (so I can close the shell and forget about it until I reboot or the connection drops)?

**Comment by ethack** [comment]
Some VPN configs take input such as password prompts or MFA which is why it starts in interactive mode. I know many don't though and I understand why you'd want the option to start it in the background.

As a workaround, you could also use something like `screen` or `tmux` to run your vpn command. Then you can close the window without killing your connection.

**Comment by giovannipizzi** [comment]
Indeed, I'm using `screen` now. I see your point and I agree that if there are interactive requests, starting in daemon mode might make things complex. I'll close this issue.
